version: '3'

services:
  serv-node0:
    container_name: serv-node0
    image: serv-chain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/node0:/root/.servchaind
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    command: >
      bash -c "
        if [ ! -d /root/.servchaind/config ]; then
          servchaind init node0 --chain-id serv-chain-1
          servchaind keys add validator0 --keyring-backend test
          servchaind add-genesis-account $(servchaind keys show validator0 -a --keyring-backend test) 10000000serv
          servchaind gentx validator0 1000000serv --chain-id serv-chain-1 --keyring-backend test
          servchaind collect-gentxs
          sed -i 's/timeout_commit = \"5s\"/timeout_commit = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/timeout_propose = \"3s\"/timeout_propose = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/index_all_keys = false/index_all_keys = true/g' /root/.servchaind/config/config.toml
          sed -i 's/enable = false/enable = true/g' /root/.servchaind/config/app.toml
          sed -i 's/swagger = false/swagger = true/g' /root/.servchaind/config/app.toml
        fi
        servchaind start --rpc.laddr tcp://0.0.0.0:26657 --api.enable
      "

  serv-node1:
    container_name: serv-node1
    image: serv-chain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/node1:/root/.servchaind
    ports:
      - "26666-26667:26656-26657"
    depends_on:
      - serv-node0
    command: >
      bash -c "
        if [ ! -d /root/.servchaind/config ]; then
          servchaind init node1 --chain-id serv-chain-1
          servchaind keys add validator1 --keyring-backend test
          servchaind add-genesis-account $(servchaind keys show validator1 -a --keyring-backend test) 10000000serv
          cp /root/.servchaind/config/genesis.json /tmp/genesis.json
          sleep 5
          wget -O /root/.servchaind/config/genesis.json http://serv-node0:26657/genesis
          SEED_NODE=$(curl -s http://serv-node0:26657/status | jq -r '.result.node_info.id')@serv-node0:26656
          sed -i 's/seeds = \"\"/seeds = \"'$SEED_NODE'\"/g' /root/.servchaind/config/config.toml
          sed -i 's/timeout_commit = \"5s\"/timeout_commit = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/timeout_propose = \"3s\"/timeout_propose = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/index_all_keys = false/index_all_keys = true/g' /root/.servchaind/config/config.toml
        fi
        servchaind start --rpc.laddr tcp://0.0.0.0:26657
      "

  serv-node2:
    container_name: serv-node2
    image: serv-chain:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/node2:/root/.servchaind
    ports:
      - "26676-26677:26656-26657"
    depends_on:
      - serv-node0
    command: >
      bash -c "
        if [ ! -d /root/.servchaind/config ]; then
          servchaind init node2 --chain-id serv-chain-1
          servchaind keys add validator2 --keyring-backend test
          servchaind add-genesis-account $(servchaind keys show validator2 -a --keyring-backend test) 10000000serv
          cp /root/.servchaind/config/genesis.json /tmp/genesis.json
          sleep 5
          wget -O /root/.servchaind/config/genesis.json http://serv-node0:26657/genesis
          SEED_NODE=$(curl -s http://serv-node0:26657/status | jq -r '.result.node_info.id')@serv-node0:26656
          sed -i 's/seeds = \"\"/seeds = \"'$SEED_NODE'\"/g' /root/.servchaind/config/config.toml
          sed -i 's/timeout_commit = \"5s\"/timeout_commit = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/timeout_propose = \"3s\"/timeout_propose = \"1s\"/g' /root/.servchaind/config/config.toml
          sed -i 's/index_all_keys = false/index_all_keys = true/g' /root/.servchaind/config/config.toml
        fi
        servchaind start --rpc.laddr tcp://0.0.0.0:26657
      "
